// Authored fixture, not generated by a model. IDs refer only to public/demo-statement.csv.
import type { Transaction } from '../../shared/transactions.js';
const fixture: Array<
  [string, string, number, Transaction['direction'], Transaction['category'], boolean]
> = [
  ['2026-09-01', 'Стипендия', 600000, 'income', 'Стипендия', true],
  ['2026-09-02', 'Общежитие', 350000, 'expense', 'Жильё', true],
  ['2026-09-03', 'Супермаркет', 125050, 'expense', 'Продукты', false],
  ['2026-09-05', 'Кофейня', 32000, 'expense', 'Кафе', false],
  ['2026-09-07', 'Проездной', 85000, 'expense', 'Транспорт', true],
  ['2026-09-10', 'Подработка дизайн', 1800000, 'income', 'Подработка', false],
  ['2026-09-12', 'Супермаркет', 184000, 'expense', 'Продукты', false],
  ['2026-09-15', 'Музыка подписка', 29900, 'expense', 'Подписки', true],
  ['2026-09-18', 'Кафе', 68000, 'expense', 'Кафе', false],
  ['2026-09-20', 'Подработка смена', 750000, 'income', 'Подработка', false],
  ['2026-09-22', 'Перевод другу', 150000, 'expense', 'Переводы', false],
  ['2026-09-24', 'Супермаркет', 96050, 'expense', 'Продукты', false],
];
export const demoResponse = {
  transactions: fixture.map(
    ([date, description, amountKopecks, direction, category, recurring], i) => ({
      sourceId: `row-${i + 1}`,
      date,
      description,
      amountKopecks,
      direction,
      category,
      recurring,
      suspicious: false,
      note: recurring ? 'Вероятная регулярность по описанию; требует проверки' : '',
    }),
  ),
  skipped: [
    {
      sourceId: 'row-13',
      reason: 'Нет знака и неизвестно направление: возврат или покупка. Уточните или исключите.',
    },
  ],
};
